from tkinter import *
root=Tk()
root.geometry("1000x1000")
frame=Frame(root,height=500,pady=30,bg='pink')
frame.pack(side=TOP,fill='x',anchor='center',pady=30,padx=20)
username=Label(frame,text="Username")
password=Label(frame,text="password")
username.grid(row=0,column=0,sticky='nw',pady=10,padx=20)
password.grid(row=1,column=0,sticky='nw',pady=10,padx=20)
uservar=StringVar()
passvar=StringVar()
username_entry=Entry(frame,textvariable=uservar)
pass_entry=Entry(frame,textvariable=passvar,show="#")
username_entry.grid(row=0,column=1,padx=10,pady=10)
pass_entry.grid(row=1,column=1,padx=10,pady=10)
root.mainloop()
